spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jwt:
    secret: o2eh1qu7yo9gthdh78u2q1o7hyua2r7uyr2q9yi7smp
    token:
      access-expiration-time: 3600000
      refresh-expiration-time: 2592000000

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}