spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: ${JWT_SECRET}
    token:
      access-expiration-time: 3600000
      refresh-expiration-time: 2592000000

file:
  upload:
    root: ./uploads
    public-prefix: /uploads

discord:
  webhook:
    url: ""

webclient:
  connection-timeout: 5000
  read-timeout: 30000  # OpenAI는 응답이 오래 걸릴 수 있음
  write-timeout: 30000

openai:
  model: gpt-4o-mini
  api:
    url: https://api.openai.com/v1
    key: ${OPENAI_API_KEY}